version: 2

# This is the root schema file for the marts directory.
# Each subdirectory (core, analytics, ml) has its own detailed schema.yml file.

groups:
  - name: core
    owner:
      name: "Data Engineering"
      email: "data@example.com"
  
  - name: analytics
    owner:
      name: "Analytics Team"
      email: "analytics@example.com"
  
  - name: ml
    owner:
      name: "ML Team"
      email: "ml@example.com"

models:
  - name: daily_player_stats
    description: "Daily aggregated batting statistics for MLB players"
    schema: marts_core
    columns:
      - name: batter_id
        description: "Unique identifier for the batter"
        tests:
          - not_null
      
      - name: player_name
        description: "Full name of the player"
        tests:
          - not_null
      
      - name: game_date
        description: "Date of the game"
        tests:
          - not_null
      
      - name: plate_appearances
        description: "Number of plate appearances"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: singles
        description: "Number of singles hit"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: doubles
        description: "Number of doubles hit"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: triples
        description: "Number of triples hit"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: home_runs
        description: "Number of home runs hit"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: walks
        description: "Number of walks"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: strikeouts
        description: "Number of strikeouts"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: total_hits
        description: "Total number of hits (singles + doubles + triples + home runs)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: batting_avg
        description: "Batting average (hits / plate appearances)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
      
      - name: on_base_pct
        description: "On-base percentage ((hits + walks) / plate appearances)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
