#api_secret_key = "api_secret_key" # please set me up!

[destination.postgres.credentials]
database = "postgres"
password = "postgres"
username = "postgres"
host = "localhost"
port = 5432
connect_timeout = 15
