api_secret_key = "api_secret_key" # please set me up!
[destination.postgres]
dataset_name = "mlb"

[destination.postgres.credentials]

database = "postgres"
username = "postgres"
password = "postgres"
host = "localhost"
port = 5432
connect_timeout = 15
